### ISSUE TITLE
libxdp doesn't build with libbpf 1.0

### ISSUE THREAD

**Issue by vcunat** [xdp-project/xdp-tools#220]
I don't think it's an issue on my side.  It worked with libbpf 0.7.0.

```
    CC       staticobjs/libxdp.o
In file included from libxdp.c:29:
include/bpf/btf.h:496:18: error: incomplete definition of type 'struct btf_enum64'
        return ((__u64)e->val_hi32 << 32) | e->val_lo32;
                       ~^
include/bpf/btf.h:489:22: note: forward declaration of 'struct btf_enum64'
static inline struct btf_enum64 *btf_enum64(const struct btf_type *t)
                     ^
```

To me that's a blocker for libbpf 1.0, as libxdp from inside of it can't be used anymore.

**Comment by tohojo** [comment]
Hmm, yeah, looks like libbpf 1.0 uses a newer version of the kernel UAPI headers. However, the new struct definition was only added in the 6.0 cycle, so it's not actually in a released kernel yet. We can work around that by updating our vendored version of the kernel headers, but this issue is going to hit anyone who tries to include the libbpf btf.h header file while using older kernel headers, so this should really be fixed in libbpf itself...

**Comment by martinetd** [comment]
Thanks for the quick fix!

FWIW they've done this on previous releases as well, which made nixos package libbpf's version of the headers if they are available, but it's not always possible or easy... silly question though: why do you also vendor these headers instead of using the system's? system's are too old for other things you need?

**Comment by tohojo** [comment]
We do this to be able to build on older distributions that ship old kernel headers. It's possible to do runtime kernel feature detection, but to do that you most often need the newer kernel headers (so you have the definitions of the stuff you're trying to probe). This is completely fine, and libbpf relying on new kernel headers is not a problem in itself. The problem here is that the dependency on the new headers has leaked into an exported header file because it's used in an inline function. This imposes the dependency on the new version of the kernel header on the application including that libbpf header file, which is the source of this bug.
